//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StoreFront.DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.OrderDetails = new HashSet<OrderDetail>();
        }
    
        public int ProductID { get; set; }
        public string Name { get; set; }
        public int CategoryID { get; set; }
        public Nullable<int> NicotineID { get; set; }
        public Nullable<int> FlavorID { get; set; }
        public decimal Price { get; set; }
        public short InStockCt { get; set; }
        public Nullable<short> OnOrderCt { get; set; }
        public Nullable<short> ReorderCt { get; set; }
        public Nullable<int> SupplierID { get; set; }
        public string Image { get; set; }
        public string Description { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Flavor Flavor { get; set; }
        public virtual Nicotine Nicotine { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
        public virtual Supplier Supplier { get; set; }
    }
}
